apiVersion: v1
kind: Service
metadata:
  # Tên Service nội bộ của API: <fullname>-api
  name: {{ include "aeos.fullname" . }}-api
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "aeos.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  # ClusterIP: Tạo Virtual IP nội bộ trong cụm K8s (không lộ ra ngoài internet)
  type: ClusterIP
  ports:
    # Service lắng nghe ở cổng tiêu chuẩn 80 (HTTP)
    - port: 80
      # Chuyển tiếp (forward) traffic vào container port có tên là 'http' (cổng 3000 của NestJS)
      targetPort: http
      protocol: TCP
      name: http
  # Selector: Tự động gom các Pod API đang khỏe mạnh (Healthy) vào danh sách Backend Endpoints
  selector:
    {{- include "aeos.api.selectorLabels" . | nindent 4 }}
