{{- if .Values.serviceAccount.create }}
# ── SERVICE ACCOUNT: ĐỊNH DANH PHÂN QUYỀN CHO POD (RBAC & CLOUD IAM) ──
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "aeos.labels" . | nindent 4 }}
  # Annotations quan trọng: Dùng để gắn role AWS IAM (ví dụ: eks.amazonaws.com/role-arn)
  # Cho phép Pod tương tác trực tiếp với AWS S3, SQS mà không cần lưu Access Key trong secret
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
