apiVersion: v1
kind: Service
metadata:
  name: {{ include "aeos.fullname" . }}-api
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "aeos.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "aeos.api.selectorLabels" . | nindent 4 }}
