apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: aeos
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: onprem
            url: https://k3s-server:6443
            valuesFile: values-onprem-prod.yaml
          - cluster: aws
            url: https://eks-endpoint.ap-southeast-1.eks.amazonaws.com
            valuesFile: values-aws-prod.yaml
  template:
    metadata:
      name: "aeos-{{cluster}}"
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/TuanStark/Adaptive-Enterprise-Operating-System.git
        targetRevision: main
        path: deploy/helm/aeos
        helm:
          valueFiles:
            - "{{valuesFile}}"
      destination:
        server: "{{url}}"
        namespace: aeos
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
        retry:
          limit: 3
          backoff:
            duration: 5s
            maxDuration: 3m
            factor: 2
